name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 1 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
        exempt-issue-labels: 'lifecycle/frozen'
        stale-issue-label: 'lifecycle/stale'
        days-before-stale: 1
        days-before-close: 5
